name: Auto Build and Push to GHCR

on:
  schedule:
    - cron: '19 7 * * 3,6' 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  check-version:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      packages: read
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag_status: ${{ steps.check_tag.outputs.tag }}
    steps:
      - name: Check latest source
        id: get_version
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/libnoname/noname/releases/latest | jq -r .tag_name)
          VERSION=${LATEST_TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest version from GitHub API: $VERSION"

      - name: Check if tag exists in GHCR
        id: check_tag
        uses: tyriis/docker-image-tag-exists@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.get_version.outputs.version }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.tag_status != 'found'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ needs.check-version.outputs.version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.check-version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
